version: '3.7'

services:

  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
    healthcheck:
      test: "exit 0"

  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT

    ports:
    - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071

    networks:
      backend:
        aliases:
          - "licenseservice"
    depends_on:
      configserver:
        condition: service_healthy

networks:
  backend:
    driver: bridge
