example:
  property: I AM THE DEFAULT

spring:
  database:
    driverClassName: org.h2.Driver
  datasource:
    platform: all
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

server:
  port: 8081

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

keycloak:
  realm: sma-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: 9e061e4d-55e5-4b71-bfef-99b38a72964f
  use-resource-role-mappings: true
  bearer-only: true

